[package]
name = "ksoft"
version = "0.1.0"
authors = ["Alvaro <62391364+AlvaroMS25@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.serde]
version = "1.0.117"

[dependencies.serde_json]
version = "1.0.59"

[dependencies.reqwest]
version = "0.10.8"

[dependencies.tokio]
version = "0.2.22"
features = ["full"]